### ISSUE TITLE
 AuthServer

### ISSUE THREAD

**Issue by fuzhiyou-69** [gvagenas/AuthServer#1]
I would like to ask you, which version of the authorization server using this OAuth2 is, and where to download the dependencies?

**Comment by gvagenas** [comment]
This is a Maven project (https://maven.apache.org/guides/getting-started/) and dependencies are defined here https://github.com/gvagenas/AuthServer/blob/main/pom.xml (Spring Authorization Server 0.2.1) 

But keep in mind that this is test/sample project to investigate whether Authorization server and be combined with Resource server which is not the recommended way to design the solution and should be avoided, check here https://stackoverflow.com/questions/70653527/spring-authorization-server-client-credentials-flow-no-session-created-on-po
